apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: cluster-projet
  labels:
    app: redis
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: user-data
          image: redis:latest
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "4m"
              memory: "500Mi"
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: cluster-projet
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP