apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-api-deployment
  namespace: cluster-projet
  labels:
    app: jobs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs-api
  template:
    metadata:
      labels:
        app: jobs-api
    spec:
      containers:
      - name: jobs-api
        image: bsu78/jobs:v1
        ports:
          - containerPort: 80
        env:
        - name: ConnectionString
          value: Server=database;User=sa;Password=Pass@word;Database=dotnetgigs.jobs;
        - name: HostRabbitmq
          value: rabbitmq-service
        resources:
          requests:
            cpu: "0.5"
            memory: "500Mi"
          limits:
            cpu: "1"
            memory: "1500Mi"
      restartPolicy: Always     
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: service-api-jobs
  namespace: cluster-projet
spec:
  selector:
    app: jobs-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP