apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: cluster-projet
  labels:
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq-pod
  template:
    metadata:
      labels:
        app: rabbitmq-pod
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
          - containerPort: 15672
          - containerPort: 5672

---

# Service
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: cluster-projet
spec:
  selector:
    app: rabbitmq-pod
  ports:
    - port: 15672
      protocol: TCP
      name: rabbitmq-port-1
      targetPort: 15672
    - port: 5672
      protocol: TCP
      name: rabbitmq-port-2
      targetPort: 5672
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: databases
  namespace: cluster-projet
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec: 
      containers:
        - name: database
          image: sayanpichaimani/db
          ports:
            - containerPort: 1433

---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: cluster-projet
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-data-api
  namespace: cluster-projet
  labels:
    app: user-data-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-data-api
  template:
    metadata:
      labels:
        app: user-data-api
    spec:
      containers:
      - image: redis
        name: user-data-api
        ports:
        - containerPort: 6379
        env:
        - name: HostRabbitmq
          value: rabbitmq-service
        resources:
          requests:
            cpu: "4m"
            memory: "500Mi"
      restartPolicy: Always  
---

apiVersion: v1
kind: Service
metadata:
  name: user-data-api
  namespace: cluster-projet
spec:
  selector:
    app: user-data-api
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api-deployment
  namespace: cluster-projet
  labels:
    app: identity-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
      - image: sayanpichaimani/identity
        name: identity-api
        ports:
          - containerPort: 80
        env:
        - name: RedisHost
          value: user-data-api:6379
        - name: HostRabbitmq
          value: rabbitmq-service
        resources:
          requests:
            cpu: "0.5"
            memory: "500Mi"
          limits:
            cpu: "1"
            memory: "1500Mi"
      restartPolicy: Always      
---

# Service
apiVersion: v1
kind: Service
metadata:
  name: service-api-identity
  namespace: cluster-projet
spec:
  selector:
    app: identity-api
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: applicants-api-deployment
  namespace: cluster-projet
  labels:
    app: applicants-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applicants-api
  template:
    metadata:
      labels:
        app: applicants-api
    spec:
      containers:
      - name: applicants-api
        image: sayanpichaimani/applicants
        env:
        - name: ConnectionString
          value: "Server=service-database;User=sa;Password=Pass@word;Database=dotnetgigs.applicants;"
        - name: HostRabbitmq
          value: rabbitmq-service
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "0.5"
            memory: "500Mi"
          limits:
            cpu: "1"
            memory: "1500Mi"
      restartPolicy: Always  
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: service-api-applicants
spec:
  selector:
    app: applicants-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-api-deployment
  namespace: cluster-projet
  labels:
    app: jobs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs-api
  template:
    metadata:
      labels:
        app: jobs-api
    spec:
      containers:
      - name: jobs-api
        image: sayanpichaimani/jobs
        ports:
          - containerPort: 80
        env:
        - name: ConnectionString
          value: Server=database;User=sa;Password=Pass@word;Database=dotnetgigs.jobs;
        - name: HostRabbitmq
          value: rabbitmq-service
        resources:
          requests:
            cpu: "0.5"
            memory: "500Mi"
          limits:
            cpu: "1"
            memory: "1500Mi"
      restartPolicy: Always     
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: service-api-jobs
  namespace: cluster-projet
spec:
  selector:
    app: jobs-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
#deployment web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: cluster-projet
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: sayanpichaimani/web
        name: web
        ports:
        - containerPort: 80
        env:
        - name: HostRabbitmq
          value: rabbitmq-api
        resources:
          requests:
            cpu: "4m"
            memory: "900Mi"
          limits:
            cpu: "1"
            memory: "2000Mi"
      restartPolicy: Always
---
#service

apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: cluster-projet
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP