apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: cluster-projet
spec:
  selector:
    app: rabbitmq-pod
  ports:
    - port: 15672
      protocol: TCP
      name: rabbitmq-port-1
      targetPort: 15672
    - port: 5672
      protocol: TCP
      name: rabbitmq-port-2
      targetPort: 5672
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: cluster-projet
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: user-data-api
  namespace: cluster-projet
spec:
  selector:
    app: user-data-api
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: service-api-identity
  namespace: cluster-projet
spec:
  selector:
    app: identity-api
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: service-api-applicants
spec:
  selector:
    app: applicants-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: service-api-jobs
  namespace: cluster-projet
spec:
  selector:
    app: jobs-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: cluster-projet
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP